ALTER TYPE "WebsiteAnalyticsEventType" ADD VALUE IF NOT EXISTS 'PROFILE_IMPRESSION';
ALTER TYPE "WebsiteAnalyticsEventType" ADD VALUE IF NOT EXISTS 'PROFILE_IMAGE_OPEN';
ALTER TYPE "WebsiteAnalyticsEventType" ADD VALUE IF NOT EXISTS 'PROFILE_WEBSITE_CLICK';
ALTER TYPE "WebsiteAnalyticsEventType" ADD VALUE IF NOT EXISTS 'PROFILE_SOCIAL_LINK_CLICK';
